// Hacemos un indice recogiendo todas las clases, asi el import será siempre igual
export * from './Profesor';
export * from './Grupo';
export * from './Alumno';
export * from './Matricula';
export * from './Equipo';
export * from './AsignacionEquipo';
export * from './Punto';
export * from './Insignia';
export * from './Juego';
export * from './AlumnoJuegoDePuntos';
export * from './Nivel';
export * from './AsignacionPuntosJuego';
export * from './EquipoJuegoDePuntos';
export * from './clasesParaTablasJuegoDePuntos/TablaAlumnoJuegoDePuntos';
export * from './HistorialPuntosAlumno';
export * from './clasesParaTablasJuegoDePuntos/TablaHistorialPuntosAlumno';
export * from './Coleccion';
export * from './Cromo';
export * from './clasesParaTablasJuegoDePuntos/TablaHistorialPuntosAlumno';
export * from './clasesParaTablasJuegoDePuntos/TablaEquipoJuegoDePuntos';
export * from './HistorialPuntosEquipo';
export * from './clasesParaTablasJuegoDePuntos/TablaHistorialPuntosEquipo';
export * from './AlumnoJuegoDeColeccion';
export * from './EquipoJuegoDeColeccion';
export * from './Album';
export * from './AlbumEquipo';
export * from './clasesParaTablasJuegoColeccion/AlbumDelAlumno';

